#!/usr/bin/env bash

if [[ "$#" -eq 3 && -d "$1/.git" ]]; then
    echo "This will squash every commit of repository \"$1\" in the master branch into one single commit, removing all history, submodules, hooks and configs in the process. The newly created repository will configure the user \"$2\" and optionally force push to remote repository \"$3\"."
    read -p "Are you sure? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        REPLY=
        mkdir -p /tmp/squashrepo
        rm -rf /tmp/squashrepo/*
        git clone -b master "$1" /tmp/squashrepo/gitrepo
        git init --bare /tmp/squashrepo/barerepo
        pushd /tmp/squashrepo/gitrepo
            find . -name "PKGBUILD" -type f -print | while read -r line; do
                srcdir=$(dirname $(readlink -f "$line"))
                pushd "$srcdir"
                    makepkg -so
                    sed -i 's/^source=\|^md5sums=\|^sha1sums=\|^sha256sums=/disabled=/g' PKGBUILD
                    sed -i 's/^pkgver\s*()/isalreadyversioned()/g' PKGBUILD
                    sed -i 's/^prepare\s*()/isalreadyprepared()/g' PKGBUILD
                popd
            done
            find . -name ".git" -type d -print | while read -r line; do
                if [[ -d "$line/refs" ]]; then
                    echo "delete gitrepo: $line"
                    rm -rf $line
                fi
            done
            find . \( -name ".git" -o -name ".gitmodules" \) -type f -print | while read -r line; do
                echo "delete file: $line"
                rm -f $line
            done
            find . -name HEAD -type f -print | while read -r line; do
                gitdir=$(dirname $(readlink -f "$line"))
                if [[ -d "$gitdir/refs" ]]; then
                    echo "delete bare gitrepo: $gitdir"
                    rm -rf $gitdir
                fi
            done
            find . -name ".github" -type d -print | while read -r line; do
                dir=$(dirname $(readlink -f "$line"))
                echo "rename github folder: \"$line\" \"$dir/.docs\""
                mv "$line" "$dir/.docs"
            done
            git init .
            git config user.name "$2"
            git config user.email "$2"
            git add -A
            git commit -am "squashed!"
            git tag -a latest HEAD -m "latest commit"
            git remote add origin "file:///tmp/squashrepo/barerepo"
            git push --set-upstream origin master -f
        popd
        pushd /tmp/squashrepo/barerepo
            git remote add origin "$3"
            read -p "Do you want to force push to \"$3\"? [y/N] " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                git push --set-upstream origin master -f
            fi
        popd
    fi
else
    echo "squashrepo [repo dir] [username] [upstream]"
fi
