#!/usr/bin/env bash

if [[ "$#" -eq 3 && -d "$1/.git" ]]; then
    echo "This will squash every commit of repository \"$1\" in the active branch into one single commit, removing all history, submodules, hooks and configs in the process. The newly created repository will configure the user \"$2\" and optionally force push to remote repository \"$3\"."
    read -p "Are you sure? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        REPLY=
        pushd "$1"
        read -p "^^-- inside here, ok?? [y/N] " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            REPLY=
            echo "okaaay, here we go..."
            sleep 2
            find . -name ".git" -type d -print | while read -r line; do
                echo "delete directory: $line"
                rm -rf $line
            done
            find . -name ".git" -type f -print | while read -r line; do
                echo "delete file: $line"
                rm -f $line
            done
            git init .
            git config user.name "$2"
            git config user.email "$2"
            git add -A
            git commit -am "squashed!"
            git tag -a latest -m "latest commit"
            git remote add origin "$3"
            read -p "Do you want to force push to \"$3\"? [y/N] " -n 1 -r
            echo
            if [[ $REPLY =~ ^[Yy]$ ]]; then
                git push --set-upstream origin master -f
            fi
        fi
        popd
    fi
else
    echo "squashrepo [repo dir] [username] [upstream]"
fi
